In [1]:
import pandas as pd
from pathlib import Path

project_folder = Path(r"C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail")

train = pd.read_csv(project_folder / "train.csv")
eval_df = pd.read_csv(project_folder / "eval.csv")

print("Train shape:", train.shape)
print("Eval shape:", eval_df.shape)

Train shape: (4500000, 19)
Eval shape: (350000, 19)

In [2]:
train["dt"] = pd.to_datetime(train["dt"])
eval_df["dt"] = pd.to_datetime(eval_df["dt"])

print(train["dt"].min(), train["dt"].max())
print(eval_df["dt"].min(), eval_df["dt"].max())

2024-03-28 00:00:00 2024-06-25 00:00:00
2024-06-26 00:00:00 2024-07-02 00:00:00

In [3]:
from pathlib import Path

project_folder = Path(r"C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail")

raw_folder = project_folder
processed_folder = project_folder / "processed"
processed_folder.mkdir(exist_ok=True)

print("Project folder:", project_folder)
print("Processed folder:", processed_folder)

Project folder: C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail
Processed folder: C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail\processed

In [4]:
daily_cols = [
    "city_id",
    "store_id",
    "management_group_id",
    "first_category_id",
    "second_category_id",
    "third_category_id",
    "product_id",
    "dt",
    "sale_amount",
    "stock_hour6_22_cnt",
    "discount",
    "holiday_flag",
    "activity_flag",
    "precpt",
    "avg_temperature",
    "avg_humidity",
    "avg_wind_level"
]

daily_train = train[daily_cols].copy()
daily_eval = eval_df[daily_cols].copy()

print("Daily train shape:", daily_train.shape)
print("Daily eval shape:", daily_eval.shape)

display(daily_train.head())

Daily train shape: (4500000, 17)
Daily eval shape: (350000, 17)

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,stock_hour6_22_cnt,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level
0,0,0,0,5,6,65,38,2024-03-28,0.1,0,1.0,0,0,1.6999,15.48,73.54,1.97
1,0,0,0,5,6,65,38,2024-03-29,0.1,1,1.0,0,0,3.0190,15.08,76.56,1.71
2,0,0,0,5,6,65,38,2024-03-30,0.0,0,1.0,1,0,2.0942,15.91,76.47,1.73
3,0,0,0,5,6,65,38,2024-03-31,0.1,11,1.0,1,0,1.5618,16.13,77.40,1.76
4,0,0,0,5,6,65,38,2024-04-01,0.2,8,1.0,0,0,3.5386,15.37,78.26,1.25

In [5]:
daily_train.to_csv(
    processed_folder / "freshretail_daily_train.csv",
    index=False,
    encoding="utf-8-sig"
)

daily_eval.to_csv(
    processed_folder / "freshretail_daily_eval.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Daily analytical CSV files saved successfully.")
print(processed_folder / "freshretail_daily_train.csv")
print(processed_folder / "freshretail_daily_eval.csv")

Daily analytical CSV files saved successfully.
C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail\processed\freshretail_daily_train.csv
C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail\processed\freshretail_daily_eval.csv

In [6]:
for file_name in ["freshretail_daily_train.csv", "freshretail_daily_eval.csv"]:
    file_path = processed_folder / file_name
    print(file_name)
    print("Exists:", file_path.exists())
    print("Size MB:", round(file_path.stat().st_size / (1024**2), 2))
    print("-" * 40)

freshretail_daily_train.csv
Exists: True
Size MB: 310.41
----------------------------------------
freshretail_daily_eval.csv
Exists: True
Size MB: 24.14
----------------------------------------

In [7]:
metadata_summary = {
    "daily_train_rows": daily_train.shape[0],
    "daily_train_columns": daily_train.shape[1],
    "daily_eval_rows": daily_eval.shape[0],
    "daily_eval_columns": daily_eval.shape[1],
    "train_start_date": daily_train["dt"].min(),
    "train_end_date": daily_train["dt"].max(),
    "eval_start_date": daily_eval["dt"].min(),
    "eval_end_date": daily_eval["dt"].max(),
    "unique_cities": daily_train["city_id"].nunique(),
    "unique_stores": daily_train["store_id"].nunique(),
    "unique_products": daily_train["product_id"].nunique(),
    "management_groups": daily_train["management_group_id"].nunique(),
    "first_categories": daily_train["first_category_id"].nunique(),
    "second_categories": daily_train["second_category_id"].nunique(),
    "third_categories": daily_train["third_category_id"].nunique()
}

metadata_summary

{'daily_train_rows': 4500000,
 'daily_train_columns': 17,
 'daily_eval_rows': 350000,
 'daily_eval_columns': 17,
 'train_start_date': Timestamp('2024-03-28 00:00:00'),
 'train_end_date': Timestamp('2024-06-25 00:00:00'),
 'eval_start_date': Timestamp('2024-06-26 00:00:00'),
 'eval_end_date': Timestamp('2024-07-02 00:00:00'),
 'unique_cities': 18,
 'unique_stores': 898,
 'unique_products': 865,
 'management_groups': 7,
 'first_categories': 32,
 'second_categories': 84,
 'third_categories': 233}

In [8]:
import pandas as pd

metadata_df = pd.DataFrame(
    list(metadata_summary.items()),
    columns=["metric", "value"]
)

metadata_df.to_csv(
    processed_folder / "freshretail_metadata_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

display(metadata_df)

                 metric                value
0      daily_train_rows              4500000
1   daily_train_columns                   17
2       daily_eval_rows               350000
3    daily_eval_columns                   17
4      train_start_date  2024-03-28 00:00:00
5        train_end_date  2024-06-25 00:00:00
6       eval_start_date  2024-06-26 00:00:00
7         eval_end_date  2024-07-02 00:00:00
8         unique_cities                   18
9         unique_stores                  898
10      unique_products                  865
11    management_groups                    7
12     first_categories                   32
13    second_categories                   84
14     third_categories                  233

In [9]:
# Basic validation for prepared daily files

print("=== Shape Check ===")
print("Daily train:", daily_train.shape)
print("Daily eval:", daily_eval.shape)

print("\n=== Missing Values - Train ===")
missing_train = pd.DataFrame({
    "missing_count": daily_train.isna().sum(),
    "missing_percent": daily_train.isna().mean() * 100
}).sort_values("missing_count", ascending=False)

display(missing_train)

print("\n=== Duplicate Grain Check ===")
train_duplicates = daily_train.duplicated(
    subset=["store_id", "product_id", "dt"]
).sum()

eval_duplicates = daily_eval.duplicated(
    subset=["store_id", "product_id", "dt"]
).sum()

print("Train duplicate store-product-date rows:", train_duplicates)
print("Eval duplicate store-product-date rows:", eval_duplicates)

print("\n=== Date Range Check ===")
print("Train:", daily_train["dt"].min(), "to", daily_train["dt"].max())
print("Eval:", daily_eval["dt"].min(), "to", daily_eval["dt"].max())

print("\n=== Value Range Checks ===")
print("sale_amount min/max:", daily_train["sale_amount"].min(), daily_train["sale_amount"].max())
print("stock_hour6_22_cnt min/max:", daily_train["stock_hour6_22_cnt"].min(), daily_train["stock_hour6_22_cnt"].max())
print("discount min/max:", daily_train["discount"].min(), daily_train["discount"].max())

print("\n=== Flag Values ===")
print("holiday_flag values:", sorted(daily_train["holiday_flag"].unique()))
print("activity_flag values:", sorted(daily_train["activity_flag"].unique()))

=== Shape Check ===
Daily train: (4500000, 17)
Daily eval: (350000, 17)

=== Missing Values - Train ===

                     missing_count  missing_percent
city_id                          0              0.0
stock_hour6_22_cnt               0              0.0
avg_humidity                     0              0.0
avg_temperature                  0              0.0
precpt                           0              0.0
activity_flag                    0              0.0
holiday_flag                     0              0.0
discount                         0              0.0
sale_amount                      0              0.0
store_id                         0              0.0
dt                               0              0.0
product_id                       0              0.0
third_category_id                0              0.0
second_category_id               0              0.0
first_category_id                0              0.0
management_group_id              0              0.0
avg_wind_level                   0              0.0

=== Duplicate Grain Check ===
Train duplicate store-product-date rows: 0
Eval duplicate store-product-date rows: 0

=== Date Range Check ===
Train: 2024-03-28 00:00:00 to 2024-06-25 00:00:00
Eval: 2024-06-26 00:00:00 to 2024-07-02 00:00:00

=== Value Range Checks ===
sale_amount min/max: 0.0 44.9
stock_hour6_22_cnt min/max: 0 16
discount min/max: 0.0 1.088

=== Flag Values ===
holiday_flag values: [0, 1]
activity_flag values: [0, 1]

In [10]:
validation_summary = {
    "daily_train_rows": daily_train.shape[0],
    "daily_train_columns": daily_train.shape[1],
    "daily_eval_rows": daily_eval.shape[0],
    "daily_eval_columns": daily_eval.shape[1],
    "train_missing_values_total": daily_train.isna().sum().sum(),
    "eval_missing_values_total": daily_eval.isna().sum().sum(),
    "train_duplicate_store_product_date": daily_train.duplicated(
        subset=["store_id", "product_id", "dt"]
    ).sum(),
    "eval_duplicate_store_product_date": daily_eval.duplicated(
        subset=["store_id", "product_id", "dt"]
    ).sum(),
    "train_start_date": daily_train["dt"].min(),
    "train_end_date": daily_train["dt"].max(),
    "eval_start_date": daily_eval["dt"].min(),
    "eval_end_date": daily_eval["dt"].max(),
    "sale_amount_min": daily_train["sale_amount"].min(),
    "sale_amount_max": daily_train["sale_amount"].max(),
    "stock_hour6_22_cnt_min": daily_train["stock_hour6_22_cnt"].min(),
    "stock_hour6_22_cnt_max": daily_train["stock_hour6_22_cnt"].max(),
    "discount_min": daily_train["discount"].min(),
    "discount_max": daily_train["discount"].max(),
    "holiday_flag_values": str(sorted(daily_train["holiday_flag"].unique())),
    "activity_flag_values": str(sorted(daily_train["activity_flag"].unique()))
}

validation_df = pd.DataFrame(
    list(validation_summary.items()),
    columns=["check", "result"]
)

validation_df.to_csv(
    processed_folder / "freshretail_preparation_validation_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

display(validation_df)

                                 check               result
0                     daily_train_rows              4500000
1                  daily_train_columns                   17
2                      daily_eval_rows               350000
3                   daily_eval_columns                   17
4           train_missing_values_total                    0
5            eval_missing_values_total                    0
6   train_duplicate_store_product_date                    0
7    eval_duplicate_store_product_date                    0
8                     train_start_date  2024-03-28 00:00:00
9                       train_end_date  2024-06-25 00:00:00
10                     eval_start_date  2024-06-26 00:00:00
11                       eval_end_date  2024-07-02 00:00:00
12                     sale_amount_min                  0.0
13                     sale_amount_max                 44.9
14              stock_hour6_22_cnt_min                    0
15              stock_hour6_22_cnt_max                   16
16                        discount_min                  0.0
17                        discount_max                1.088
18                 holiday_flag_values               [0, 1]
19                activity_flag_values               [0, 1]