In [3]:
import sys
import subprocess

print(sys.executable)

subprocess.check_call([
    sys.executable,
    "-m",
    "pip",
    "install",
    "sqlalchemy",
    "pymysql"
])

\\?\C:\Users\safwatr\AppData\Roaming\jupyterlab-desktop\jlab_server\python.exe

0

In [1]:
import sqlalchemy
import pymysql

print("Packages installed successfully")

Packages installed successfully

In [7]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus
import pandas as pd

password = quote_plus("Roma@1357")

engine = create_engine(
    f"mysql+pymysql://root:{password}@127.0.0.1:3306/freshretail_db"
)

test = pd.read_sql("SELECT DATABASE() AS db_name;", engine)
display(test)

          db_name
0  freshretail_db

In [8]:
from pathlib import Path
import pandas as pd

processed_folder = Path(r"C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail\processed")

eval_path = processed_folder / "freshretail_daily_eval.csv"

for i, chunk in enumerate(pd.read_csv(eval_path, chunksize=50000)):
    chunk["dt"] = pd.to_datetime(chunk["dt"]).dt.date
    
    chunk.to_sql(
        name="freshretail_daily_eval",
        con=engine,
        if_exists="append",
        index=False,
        chunksize=5000
    )
    
    print(f"Chunk {i+1} inserted, rows: {len(chunk)}")

print("Eval import completed")

Chunk 1 inserted, rows: 50000
Chunk 2 inserted, rows: 50000
Chunk 3 inserted, rows: 50000
Chunk 4 inserted, rows: 50000
Chunk 5 inserted, rows: 50000
Chunk 6 inserted, rows: 50000
Chunk 7 inserted, rows: 50000
Eval import completed

In [9]:
count_eval = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM freshretail_daily_eval;",
    engine
)

display(count_eval)

   total_rows
0      350000

In [10]:
import pandas as pd

count_train_before = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM freshretail_daily_train;",
    engine
)

display(count_train_before)

   total_rows
0           0

In [11]:
from pathlib import Path
import pandas as pd
import time

processed_folder = Path(r"C:\Users\safwatr\IntelGraphicsProfiles\Fresh Retail\processed")

train_path = processed_folder / "freshretail_daily_train.csv"

start_time = time.time()

for i, chunk in enumerate(pd.read_csv(train_path, chunksize=50000)):
    chunk["dt"] = pd.to_datetime(chunk["dt"]).dt.date
    
    chunk.to_sql(
        name="freshretail_daily_train",
        con=engine,
        if_exists="append",
        index=False,
        chunksize=5000
    )
    
    print(f"Chunk {i+1} inserted, rows: {len(chunk)}")

end_time = time.time()

print("Train import completed")
print("Total time minutes:", round((end_time - start_time) / 60, 2))

Chunk 1 inserted, rows: 50000
Chunk 2 inserted, rows: 50000
Chunk 3 inserted, rows: 50000
Chunk 4 inserted, rows: 50000
Chunk 5 inserted, rows: 50000
Chunk 6 inserted, rows: 50000
Chunk 7 inserted, rows: 50000
Chunk 8 inserted, rows: 50000
Chunk 9 inserted, rows: 50000
Chunk 10 inserted, rows: 50000
Chunk 11 inserted, rows: 50000
Chunk 12 inserted, rows: 50000
Chunk 13 inserted, rows: 50000
Chunk 14 inserted, rows: 50000
Chunk 15 inserted, rows: 50000
Chunk 16 inserted, rows: 50000
Chunk 17 inserted, rows: 50000
Chunk 18 inserted, rows: 50000
Chunk 19 inserted, rows: 50000
Chunk 20 inserted, rows: 50000
Chunk 21 inserted, rows: 50000
Chunk 22 inserted, rows: 50000
Chunk 23 inserted, rows: 50000
Chunk 24 inserted, rows: 50000
Chunk 25 inserted, rows: 50000
Chunk 26 inserted, rows: 50000
Chunk 27 inserted, rows: 50000
Chunk 28 inserted, rows: 50000
Chunk 29 inserted, rows: 50000
Chunk 30 inserted, rows: 50000
Chunk 31 inserted, rows: 50000
Chunk 32 inserted, rows: 50000
Chunk 33 inserted, rows: 50000
Chunk 34 inserted, rows: 50000
Chunk 35 inserted, rows: 50000
Chunk 36 inserted, rows: 50000
Chunk 37 inserted, rows: 50000
Chunk 38 inserted, rows: 50000
Chunk 39 inserted, rows: 50000
Chunk 40 inserted, rows: 50000
Chunk 41 inserted, rows: 50000
Chunk 42 inserted, rows: 50000
Chunk 43 inserted, rows: 50000
Chunk 44 inserted, rows: 50000
Chunk 45 inserted, rows: 50000
Chunk 46 inserted, rows: 50000
Chunk 47 inserted, rows: 50000
Chunk 48 inserted, rows: 50000
Chunk 49 inserted, rows: 50000
Chunk 50 inserted, rows: 50000
Chunk 51 inserted, rows: 50000
Chunk 52 inserted, rows: 50000
Chunk 53 inserted, rows: 50000
Chunk 54 inserted, rows: 50000
Chunk 55 inserted, rows: 50000
Chunk 56 inserted, rows: 50000
Chunk 57 inserted, rows: 50000
Chunk 58 inserted, rows: 50000
Chunk 59 inserted, rows: 50000
Chunk 60 inserted, rows: 50000
Chunk 61 inserted, rows: 50000
Chunk 62 inserted, rows: 50000
Chunk 63 inserted, rows: 50000
Chunk 64 inserted, rows: 50000
Chunk 65 inserted, rows: 50000
Chunk 66 inserted, rows: 50000
Chunk 67 inserted, rows: 50000
Chunk 68 inserted, rows: 50000
Chunk 69 inserted, rows: 50000
Chunk 70 inserted, rows: 50000
Chunk 71 inserted, rows: 50000
Chunk 72 inserted, rows: 50000
Chunk 73 inserted, rows: 50000
Chunk 74 inserted, rows: 50000
Chunk 75 inserted, rows: 50000
Chunk 76 inserted, rows: 50000
Chunk 77 inserted, rows: 50000
Chunk 78 inserted, rows: 50000
Chunk 79 inserted, rows: 50000
Chunk 80 inserted, rows: 50000
Chunk 81 inserted, rows: 50000
Chunk 82 inserted, rows: 50000
Chunk 83 inserted, rows: 50000
Chunk 84 inserted, rows: 50000
Chunk 85 inserted, rows: 50000
Chunk 86 inserted, rows: 50000
Chunk 87 inserted, rows: 50000
Chunk 88 inserted, rows: 50000
Chunk 89 inserted, rows: 50000
Chunk 90 inserted, rows: 50000
Train import completed
Total time minutes: 11.25

In [12]:
count_train = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM freshretail_daily_train;",
    engine
)

display(count_train)

   total_rows
0     4500000